/** Audit log actions (doc 30 AD13) in words. Unknown actions show as recorded. */
const LABELS: Record<string, string> = {
  "auth.register": "made an account",
  "auth.login": "signed in",
  "auth.reset_password": "set a new password with a reset code",
  "auth.session_end": "signed out a browser",
  "auth.steam_link": "linked Steam",
  "auth.steam_unlink": "unlinked Steam",
  "user.update": "changed their profile",
  "user.export": "downloaded their data",
  "user.delete": "deleted their account",
  "study.consent": "agreed to the study",
  "match.rename": "renamed a match",
  "match.delete": "deleted a match",
  "match.share": "made a share link",
  "match.unshare": "turned off a share link",
  "admin.user_update": "changed a user",
  "admin.user_signout": "signed a user out everywhere",
  "admin.user_reset": "made a reset code",
  "admin.user_delete": "deleted a user",
  "admin.invites_create": "made invites",
  "admin.invite_revoke": "withdrew an invite",
  "admin.match_owner": "changed a match's owner",
  "admin.match_delete": "deleted a match",
  "admin.match_reprocess": "reprocessed a match",
  "admin.job_cancel": "cancelled a job",
  "admin.clip_retry": "retried a clip",
  "admin.setting": "changed a setting",
  "admin.setting_reset": "reset a setting",
  "admin.note_edit": "edited a map note",
  "admin.note_delete": "deleted a map note",
  "admin.flag_resolve": "resolved a flagged passage",
  "admin.knowledge_rebuild": "rebuilt the knowledge index",
  "admin.study_export": "exported the study CSV",
  "admin.cleanup": "cleaned up storage",
  "admin.backup": "made a backup",
  "admin.restore": "restored a backup",
  "admin.session_end": "ended a session",
  "admin.token_create": "made an API token",
  "admin.token_revoke": "revoked an API token",
};

export function auditLabel(action: string): string {
  return LABELS[action] ?? action;
}
